# Generated by Django 5.1.15 on 2026-04-10 11:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.UUIDField(db_index=True)),
                ('case_number', models.CharField(blank=True, max_length=100)),
                ('user_id', models.UUIDField(db_index=True)),
                ('task_type', models.CharField(choices=[('research', 'Investigación'), ('drafting', 'Redacción de documentos'), ('court', 'Actuación judicial'), ('client_meeting', 'Reunión con cliente'), ('negotiation', 'Negociación'), ('review', 'Revisión y análisis'), ('admin', 'Gestión administrativa'), ('travel', 'Desplazamiento'), ('other', 'Otro')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_billable', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('running', 'En curso'), ('paused', 'Pausado'), ('stopped', 'Detenido')], default='running', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('accumulated_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'status'], name='time_tracki_user_id_087c31_idx'), models.Index(fields=['case_id', 'status'], name='time_tracki_case_id_a33074_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.UUIDField(db_index=True)),
                ('case_number', models.CharField(blank=True, max_length=100)),
                ('user_id', models.UUIDField(db_index=True)),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('task_type', models.CharField(choices=[('research', 'Investigación'), ('drafting', 'Redacción de documentos'), ('court', 'Actuación judicial'), ('client_meeting', 'Reunión con cliente'), ('negotiation', 'Negociación'), ('review', 'Revisión y análisis'), ('admin', 'Gestión administrativa'), ('travel', 'Desplazamiento'), ('other', 'Otro')], default='other', max_length=30)),
                ('description', models.TextField()),
                ('date', models.DateField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('is_billable', models.BooleanField(default=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa por hora en EUR. Null = usar tarifa del cliente.', max_digits=10, null=True)),
                ('created_from_timer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entry', to='time_tracking.timer')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['case_id', 'date'], name='time_tracki_case_id_f8b788_idx'), models.Index(fields=['user_id', 'date'], name='time_tracki_user_id_60c1d3_idx'), models.Index(fields=['case_id', 'is_billable'], name='time_tracki_case_id_635e54_idx')],
            },
        ),
    ]
