# Generated by Django 5.1.15 on 2026-04-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='lawyer_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
