# Generated by Django 5.1.15 on 2026-04-17 15:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('case_date_id', models.UUIDField(blank=True, help_text='ID del CaseDate del Matter Service (si viene sincronizado)', null=True)),
                ('assigned_to', models.UUIDField(db_index=True, help_text='user_id del responsable')),
                ('created_by', models.UUIDField()),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('hearing', 'Audiencia'), ('deadline', 'Plazo procesal'), ('filing', 'Escrito / Presentación'), ('trial', 'Juicio oral'), ('appeal', 'Recurso'), ('notification', 'Notificación'), ('meeting', 'Reunión'), ('payment', 'Vencimiento de pago'), ('other', 'Otro')], default='other', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('is_legal_deadline', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('case_number', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'calendar_events',
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['assigned_to', 'start_datetime'], name='calendar_ev_assigne_8241ae_idx'), models.Index(fields=['case_id', 'start_datetime'], name='calendar_ev_case_id_3db195_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remind_before_value', models.PositiveIntegerField(default=1)),
                ('remind_before_unit', models.CharField(choices=[('minutes', 'Minutos'), ('hours', 'Horas'), ('days', 'Días')], default='days', max_length=10)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='calendar_app.calendarevent')),
            ],
            options={
                'db_table': 'event_reminders',
            },
        ),
    ]
