# Generated by Django 5.1.15 on 2026-04-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='assigned_to',
            field=models.UUIDField(blank=True, db_index=True, help_text='user_id del responsable', null=True),
        ),
    ]
