# Generated by Django 5.1.15 on 2026-04-10 07:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('case_number', models.CharField(help_text='Número de expediente oficial', max_length=100, unique=True)),
                ('case_type', models.CharField(choices=[('civil', 'Civil'), ('criminal', 'Penal'), ('corporate', 'Corporativo'), ('family', 'Familia'), ('labor', 'Laboral'), ('administrative', 'Administrativo'), ('constitutional', 'Constitucional'), ('other', 'Otro')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En proceso'), ('on_hold', 'En espera'), ('in_appeal', 'En apelación'), ('closed', 'Cerrado'), ('archived', 'Archivado')], default='open', max_length=30)),
                ('jurisdiction', models.CharField(blank=True, help_text='Jurisdicción o tribunal competente', max_length=200)),
                ('court', models.CharField(blank=True, help_text='Juzgado o tribunal asignado', max_length=200)),
                ('assigned_lawyer_id', models.UUIDField(help_text='ID del abogado responsable (IAM Service)')),
                ('client_id', models.UUIDField(help_text='ID del cliente (IAM Service)')),
                ('opened_at', models.DateField(help_text='Fecha de apertura del caso')),
                ('closed_at', models.DateField(blank=True, help_text='Fecha de cierre del caso', null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Etiquetas para clasificación y búsqueda')),
                ('notes', models.TextField(blank=True, help_text='Notas internas del caso')),
                ('is_urgent', models.BooleanField(default=False, help_text='Marca el caso como urgente')),
                ('created_by', models.UUIDField(help_text='ID del usuario que creó el caso (IAM Service)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
                'db_table': 'cases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='cases_status_e2ca9e_idx'), models.Index(fields=['case_type'], name='cases_case_ty_37d3f0_idx'), models.Index(fields=['assigned_lawyer_id'], name='cases_assigne_e69e63_idx'), models.Index(fields=['client_id'], name='cases_client__260b2c_idx'), models.Index(fields=['opened_at'], name='cases_opened__770ade_idx')],
            },
        ),
        migrations.CreateModel(
            name='CaseParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('client', 'Cliente'), ('opposing_party', 'Parte contraria'), ('lawyer', 'Abogado'), ('prosecutor', 'Procurador'), ('witness', 'Testigo'), ('expert', 'Perito'), ('judge', 'Juez'), ('other', 'Otro')], default='other', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('identification', models.CharField(blank=True, help_text='DNI, NIF, pasaporte u otro identificador', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('user_id', models.UUIDField(blank=True, help_text='ID del usuario en IAM Service (si aplica)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='matters.case')),
            ],
            options={
                'verbose_name': 'Parte del Caso',
                'verbose_name_plural': 'Partes del Caso',
                'db_table': 'case_parties',
                'ordering': ['role', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='CaseActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('created', 'Caso creado'), ('updated', 'Caso actualizado'), ('status_changed', 'Estado cambiado'), ('party_added', 'Parte añadida'), ('party_removed', 'Parte eliminada'), ('date_added', 'Fecha añadida'), ('date_completed', 'Fecha completada'), ('closed', 'Caso cerrado'), ('reopened', 'Caso reabierto'), ('assigned', 'Caso reasignado')], max_length=30)),
                ('user_id', models.UUIDField(help_text='Usuario que realizó la acción')),
                ('description', models.TextField()),
                ('old_value', models.JSONField(blank=True, help_text='Valor anterior (para cambios de estado/asignación)', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='Valor nuevo (para cambios de estado/asignación)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='matters.case')),
            ],
            options={
                'verbose_name': 'Log de Actividad',
                'verbose_name_plural': 'Logs de Actividad',
                'db_table': 'case_activity_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['case', '-timestamp'], name='case_activi_case_id_caaa0c_idx'), models.Index(fields=['user_id', '-timestamp'], name='case_activi_user_id_0c6282_idx'), models.Index(fields=['activity_type'], name='case_activi_activit_b4c82e_idx')],
            },
        ),
        migrations.CreateModel(
            name='CaseDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_type', models.CharField(choices=[('hearing', 'Audiencia'), ('deadline', 'Plazo procesal'), ('filing', 'Presentación de escrito'), ('trial', 'Juicio oral'), ('appeal', 'Recurso de apelación'), ('notification', 'Notificación'), ('meeting', 'Reunión con cliente'), ('other', 'Otro')], default='other', max_length=30)),
                ('scheduled_date', models.DateTimeField(help_text='Fecha y hora del evento')),
                ('is_critical', models.BooleanField(default=False, help_text='Fecha crítica que requiere atención inmediata')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.UUIDField(help_text='ID del usuario que creó la fecha (IAM Service)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='matters.case')),
            ],
            options={
                'verbose_name': 'Fecha del Caso',
                'verbose_name_plural': 'Fechas del Caso',
                'db_table': 'case_dates',
                'ordering': ['scheduled_date'],
                'indexes': [models.Index(fields=['case', 'scheduled_date'], name='case_dates_case_id_ec218b_idx'), models.Index(fields=['is_critical', 'is_completed'], name='case_dates_is_crit_befa49_idx'), models.Index(fields=['date_type'], name='case_dates_date_ty_38101c_idx')],
            },
        ),
    ]
