# Generated by Django 5.1.15 on 2026-04-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedate',
            name='calendar_event_id',
            field=models.UUIDField(blank=True, help_text='ID del evento sincronizado en el Calendar Service', null=True),
        ),
    ]
