# Generated by Django 5.1.15 on 2026-03-20 11:33

import apps.documents.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('contract', 'Contrato'), ('lawsuit', 'Demanda'), ('brief', 'Escrito'), ('evidence', 'Prueba'), ('ruling', 'Sentencia'), ('power_of_attorney', 'Poder Notarial'), ('invoice', 'Factura'), ('correspondence', 'Correspondencia'), ('other', 'Otro')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('review', 'En revisión'), ('approved', 'Aprobado'), ('signed', 'Firmado'), ('archived', 'Archivado')], default='draft', max_length=20)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField(help_text='Tamaño en bytes')),
                ('file_hash', models.CharField(help_text='SHA-256 del contenido del archivo', max_length=64)),
                ('case_id', models.UUIDField(db_index=True, help_text='ID del caso en el Matter Service')),
                ('uploaded_by', models.UUIDField(help_text='ID del usuario que subió el documento (del IAM Service)')),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('is_confidential', models.BooleanField(default=False, help_text='Documentos confidenciales requieren permisos adicionales')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Etiquetas para búsqueda y clasificación')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadatos adicionales del documento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case_id', '-created_at'], name='documents_case_id_ad94d4_idx'), models.Index(fields=['document_type'], name='documents_documen_fc21d0_idx'), models.Index(fields=['uploaded_by'], name='documents_uploade_f550b6_idx'), models.Index(fields=['status'], name='documents_status_f31a08_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_title', models.CharField(help_text='Snapshot del título en el momento del acceso', max_length=255)),
                ('user_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('view', 'Visualización'), ('download', 'Descarga'), ('upload', 'Subida'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('version_create', 'Creación de versión'), ('permission_check', 'Verificación de permiso')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Información adicional sobre la acción')),
                ('success', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='documents.document')),
            ],
            options={
                'verbose_name': 'Log de Acceso',
                'verbose_name_plural': 'Logs de Acceso',
                'db_table': 'document_access_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', '-timestamp'], name='document_ac_user_id_171b48_idx'), models.Index(fields=['document', '-timestamp'], name='document_ac_documen_fbc874_idx'), models.Index(fields=['action'], name='document_ac_action_4daaa6_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='documents/versions/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('file_hash', models.CharField(max_length=64)),
                ('change_summary', models.TextField(blank=True, help_text='Descripción de los cambios en esta versión')),
                ('created_by', models.UUIDField(help_text='ID del usuario que creó esta versión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'verbose_name': 'Versión de Documento',
                'verbose_name_plural': 'Versiones de Documentos',
                'db_table': 'document_versions',
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
